package com.mps.model;
// Generated 2016-6-24 20:12:03 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Agency generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy=false)
@Table(name = "agency", catalog = "planeticketreserve")
@XmlRootElement(name="Agency")
public class Agency implements java.io.Serializable {

	private Integer id;
	private String pwd;
	private String name;
	private String address;
	private String contacts;
	private String phone;
	/*private Set<Team> teams = new HashSet<Team>();
	private Set<Traveller> travellers = new HashSet<Traveller>();
*/
	public Agency() {
	}

	public Agency(String pwd, String name, String address, String contacts, String phone) {
		this.pwd = pwd;
		this.name = name;
		this.address = address;
		this.contacts = contacts;
		this.phone = phone;
		/*this.teams = teams;
		this.travellers = travellers;*/
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "pwd", length = 25)
	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "contacts")
	public String getContacts() {
		return this.contacts;
	}

	public void setContacts(String contacts) {
		this.contacts = contacts;
	}

	@Column(name = "phone", length = 25)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

}
