package com.mps.model;
// Generated 2016-6-18 9:41:43 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Agency generated by hbm2java
 */
@XmlRootElement(name="Agency")
public class Agency implements java.io.Serializable {
	private static final long serialVersionUID = -3267943602377867497L;
	private Integer id;
	private String pwd;
	private String name;
	private String address;
	private String contacts;
	private String phone;
	private Set teams = new HashSet(0);
	private Set travellers = new HashSet(0);

	public Agency() {
	}

	public Agency(String pwd, String name, String address, String contacts, String phone, Set teams, Set travellers) {
		this.pwd = pwd;
		this.name = name;
		this.address = address;
		this.contacts = contacts;
		this.phone = phone;
		this.teams = teams;
		this.travellers = travellers;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getContacts() {
		return this.contacts;
	}

	public void setContacts(String contacts) {
		this.contacts = contacts;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Set getTeams() {
		return this.teams;
	}

	public void setTeams(Set teams) {
		this.teams = teams;
	}

	public Set getTravellers() {
		return this.travellers;
	}

	public void setTravellers(Set travellers) {
		this.travellers = travellers;
	}

}
