package com.mps.model;
// Generated 2016-6-24 20:12:03 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Orders generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy=false)
@Table(name = "orders", catalog = "planeticketreserve")
@XmlRootElement(name="Orders")
public class Orders implements java.io.Serializable {

	private Integer id;
	private Team team;
	private Traveller traveller;
	private String flight;
	private String startpoint;
	private String endpoint;
	private Date starttime;
	private Date endtime;
	private Integer advancestatus;
	private Integer ticketstatus;
	private Date tickettime;
	private Double price;
	private Integer seat;
	private Integer space;

	public Orders() {
	}

	public Orders(Team team, Traveller traveller) {
		this.team = team;
		this.traveller = traveller;
	}

	public Orders(Team team, Traveller traveller, String flight, String startpoint, String endpoint, Date starttime,
			Date endtime, Integer advancestatus, Integer ticketstatus, Date tickettime, Double price, Integer seat,
			Integer space) {
		this.team = team;
		this.traveller = traveller;
		this.flight = flight;
		this.startpoint = startpoint;
		this.endpoint = endpoint;
		this.starttime = starttime;
		this.endtime = endtime;
		this.advancestatus = advancestatus;
		this.ticketstatus = ticketstatus;
		this.tickettime = tickettime;
		this.price = price;
		this.seat = seat;
		this.space = space;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "teamid", nullable = false)
	public Team getTeam() {
		return this.team;
	}

	public void setTeam(Team team) {
		this.team = team;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "travellerid", nullable = false)
	public Traveller getTraveller() {
		return this.traveller;
	}

	public void setTraveller(Traveller traveller) {
		this.traveller = traveller;
	}

	@Column(name = "flight", length = 25)
	public String getFlight() {
		return this.flight;
	}

	public void setFlight(String flight) {
		this.flight = flight;
	}

	@Column(name = "startpoint", length = 25)
	public String getStartpoint() {
		return this.startpoint;
	}

	public void setStartpoint(String startpoint) {
		this.startpoint = startpoint;
	}

	@Column(name = "endpoint", length = 25)
	public String getEndpoint() {
		return this.endpoint;
	}

	public void setEndpoint(String endpoint) {
		this.endpoint = endpoint;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "starttime", length = 19)
	public Date getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "endtime", length = 19)
	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	@Column(name = "advancestatus")
	public Integer getAdvancestatus() {
		return this.advancestatus;
	}

	public void setAdvancestatus(Integer advancestatus) {
		this.advancestatus = advancestatus;
	}

	@Column(name = "ticketstatus")
	public Integer getTicketstatus() {
		return this.ticketstatus;
	}

	public void setTicketstatus(Integer ticketstatus) {
		this.ticketstatus = ticketstatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tickettime", length = 19)
	public Date getTickettime() {
		return this.tickettime;
	}

	public void setTickettime(Date tickettime) {
		this.tickettime = tickettime;
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "seat")
	public Integer getSeat() {
		return this.seat;
	}

	public void setSeat(Integer seat) {
		this.seat = seat;
	}

	@Column(name = "space")
	public Integer getSpace() {
		return this.space;
	}

	public void setSpace(Integer space) {
		this.space = space;
	}

}
