package com.mps.model;
// Generated 2016-6-18 9:41:43 by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Orders generated by hbm2java
 */

@XmlRootElement(name="Orders")
public class Orders implements java.io.Serializable {
	private static final long serialVersionUID = -3267943602377867496L;
	private Integer id;
	private Team team;
	private Traveller traveller;
	private String flight;
	private String startpoint;
	private String endpoint;
	private Date starttime;
	private Date endtime;
	private Integer advancestatus;
	private Integer ticketstatus;
	private Date tickettime;
	private Double price;
	private Integer seat;
	private Integer space;

	public Orders() {
	}

	public Orders(Team team, Traveller traveller) {
		this.team = team;
		this.traveller = traveller;
	}

	public Orders(Team team, Traveller traveller, String flight, String startpoint, String endpoint, Date starttime,
			Date endtime, Integer advancestatus, Integer ticketstatus, Date tickettime, Double price, Integer seat,
			Integer space) {
		this.team = team;
		this.traveller = traveller;
		this.flight = flight;
		this.startpoint = startpoint;
		this.endpoint = endpoint;
		this.starttime = starttime;
		this.endtime = endtime;
		this.advancestatus = advancestatus;
		this.ticketstatus = ticketstatus;
		this.tickettime = tickettime;
		this.price = price;
		this.seat = seat;
		this.space = space;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Team getTeam() {
		return this.team;
	}

	public void setTeam(Team team) {
		this.team = team;
	}

	public Traveller getTraveller() {
		return this.traveller;
	}

	public void setTraveller(Traveller traveller) {
		this.traveller = traveller;
	}

	public String getFlight() {
		return this.flight;
	}

	public void setFlight(String flight) {
		this.flight = flight;
	}

	public String getStartpoint() {
		return this.startpoint;
	}

	public void setStartpoint(String startpoint) {
		this.startpoint = startpoint;
	}

	public String getEndpoint() {
		return this.endpoint;
	}

	public void setEndpoint(String endpoint) {
		this.endpoint = endpoint;
	}

	public Date getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	public Integer getAdvancestatus() {
		return this.advancestatus;
	}

	public void setAdvancestatus(Integer advancestatus) {
		this.advancestatus = advancestatus;
	}

	public Integer getTicketstatus() {
		return this.ticketstatus;
	}

	public void setTicketstatus(Integer ticketstatus) {
		this.ticketstatus = ticketstatus;
	}

	public Date getTickettime() {
		return this.tickettime;
	}

	public void setTickettime(Date tickettime) {
		this.tickettime = tickettime;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Integer getSeat() {
		return this.seat;
	}

	public void setSeat(Integer seat) {
		this.seat = seat;
	}

	public Integer getSpace() {
		return this.space;
	}

	public void setSpace(Integer space) {
		this.space = space;
	}

}
