package com.mps.model;
// Generated 2016-6-17 8:20:37 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Participate generated by hbm2java
 */
public class Participate implements java.io.Serializable {

	private ParticipateId id;
	private Team team;
	private Traveller traveller;
	private Date jointime;

	public Participate() {
	}

	public Participate(ParticipateId id, Team team, Traveller traveller) {
		this.id = id;
		this.team = team;
		this.traveller = traveller;
	}

	public Participate(ParticipateId id, Team team, Traveller traveller, Date jointime) {
		this.id = id;
		this.team = team;
		this.traveller = traveller;
		this.jointime = jointime;
	}

	public ParticipateId getId() {
		return this.id;
	}

	public void setId(ParticipateId id) {
		this.id = id;
	}

	public Team getTeam() {
		return this.team;
	}

	public void setTeam(Team team) {
		this.team = team;
	}

	public Traveller getTraveller() {
		return this.traveller;
	}

	public void setTraveller(Traveller traveller) {
		this.traveller = traveller;
	}

	public Date getJointime() {
		return this.jointime;
	}

	public void setJointime(Date jointime) {
		this.jointime = jointime;
	}

}
