package com.mps.model;
// Generated 2016-6-24 20:12:03 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Participate generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy=false)
@Table(name = "participate", catalog = "planeticketreserve")
@XmlRootElement(name="Participate")
public class Participate implements java.io.Serializable {

	private Integer id;
	private Team team;
	private Traveller traveller;
	private Date jointime;

	public Participate() {
	}

	public Participate(Team team, Traveller traveller, Date jointime) {
		this.team = team;
		this.traveller = traveller;
		this.jointime = jointime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "teamid", nullable = false)
	public Team getTeam() {
		return this.team;
	}

	public void setTeam(Team team) {
		this.team = team;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "travellerid", nullable = false)
	public Traveller getTraveller() {
		return this.traveller;
	}

	public void setTraveller(Traveller traveller) {
		this.traveller = traveller;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "jointime", nullable = false, length = 19)
	public Date getJointime() {
		return this.jointime;
	}

	public void setJointime(Date jointime) {
		this.jointime = jointime;
	}

}
