package com.mps.model;
// Generated 2016-6-17 8:20:37 by Hibernate Tools 4.3.1.Final

/**
 * ParticipateId generated by hbm2java
 */
public class ParticipateId implements java.io.Serializable {

	private int travellerid;
	private int teamid;

	public ParticipateId() {
	}

	public ParticipateId(int travellerid, int teamid) {
		this.travellerid = travellerid;
		this.teamid = teamid;
	}

	public int getTravellerid() {
		return this.travellerid;
	}

	public void setTravellerid(int travellerid) {
		this.travellerid = travellerid;
	}

	public int getTeamid() {
		return this.teamid;
	}

	public void setTeamid(int teamid) {
		this.teamid = teamid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ParticipateId))
			return false;
		ParticipateId castOther = (ParticipateId) other;

		return (this.getTravellerid() == castOther.getTravellerid()) && (this.getTeamid() == castOther.getTeamid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTravellerid();
		result = 37 * result + this.getTeamid();
		return result;
	}

}
