package com.mps.model;
// Generated 2016-6-24 20:12:03 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Route generated by hbm2java
 */
@Entity
@org.hibernate.annotations.Proxy(lazy=false)
@Table(name = "route", catalog = "planeticketreserve")
@XmlRootElement(name="Route")
public class Route implements java.io.Serializable {

	private Integer id;
	private Team team;
	private String startpoint;
	private String endpoint;
	private Integer ordernumber;

	public Route() {
	}

	public Route(Team team) {
		this.team = team;
	}

	public Route(Team team, String startpoint, String endpoint, Integer ordernumber) {
		this.team = team;
		this.startpoint = startpoint;
		this.endpoint = endpoint;
		this.ordernumber = ordernumber;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "teamid", nullable = false)
	public Team getTeam() {
		return this.team;
	}

	public void setTeam(Team team) {
		this.team = team;
	}

	@Column(name = "startpoint", length = 25)
	public String getStartpoint() {
		return this.startpoint;
	}

	public void setStartpoint(String startpoint) {
		this.startpoint = startpoint;
	}

	@Column(name = "endpoint", length = 25)
	public String getEndpoint() {
		return this.endpoint;
	}

	public void setEndpoint(String endpoint) {
		this.endpoint = endpoint;
	}

	@Column(name = "ordernumber")
	public Integer getOrdernumber() {
		return this.ordernumber;
	}

	public void setOrdernumber(Integer ordernumber) {
		this.ordernumber = ordernumber;
	}

}
