package com.mps.model;
// Generated 2016-6-18 9:41:43 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Team generated by hbm2java
 */
@XmlRootElement(name="Team")
public class Team implements java.io.Serializable {
	private static final long serialVersionUID = -3267943602377867493L;
	
	private Integer id;
	private Agency agency;
	private String name;
	private Date starttime;
	private Date endtime;
	private Integer type;
	private Integer status;
	private Set orderses = new HashSet(0);
	private Set participates = new HashSet(0);
	private Set routes = new HashSet(0);

	public Team() {
	}

	public Team(Agency agency) {
		this.agency = agency;
	}

	public Team(Agency agency, String name, Date starttime, Date endtime, Integer type, Integer status, Set orderses,
			Set participates, Set routes) {
		this.agency = agency;
		this.name = name;
		this.starttime = starttime;
		this.endtime = endtime;
		this.type = type;
		this.status = status;
		this.orderses = orderses;
		this.participates = participates;
		this.routes = routes;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Agency getAgency() {
		return this.agency;
	}

	public void setAgency(Agency agency) {
		this.agency = agency;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Set getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set orderses) {
		this.orderses = orderses;
	}

	public Set getParticipates() {
		return this.participates;
	}

	public void setParticipates(Set participates) {
		this.participates = participates;
	}

	public Set getRoutes() {
		return this.routes;
	}

	public void setRoutes(Set routes) {
		this.routes = routes;
	}

}
